/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;

/**
 *
 * @author DADO
 */
public class CheckIn extends javax.swing.JFrame {
    
    private Customer customer;
    private Room room;
    private double price;
    
    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateFromField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        dateToField = new javax.swing.JFormattedTextField();
        setCustomer = new javax.swing.JButton();
        setRoom = new javax.swing.JButton();
        customerChosen = new javax.swing.JLabel();
        roomChosen = new javax.swing.JLabel();
        createReservationBtn = new javax.swing.JButton();
        createAccmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        priceAccmLbl = new javax.swing.JLabel();
        fromReservationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Dátum od:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        try {
            dateFromField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(dateFromField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        jLabel2.setText("Dátum do:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        try {
            dateToField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(dateToField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, -1));

        setCustomer.setText("Vybrať zákazníka");
        getContentPane().add(setCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        setRoom.setText("Vybrať izbu");
        getContentPane().add(setRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(customerChosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 20));
        getContentPane().add(roomChosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 20));

        createReservationBtn.setText("Len rezervovať");
        getContentPane().add(createReservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        createAccmBtn.setText("Ubytovať");
        getContentPane().add(createAccmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        cancelBtn.setText("Zrušiť");
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel5.setText("Cena za ubytovanie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(priceAccmLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, 20));

        fromReservationBtn.setText("Vytvoriť z rezervácie");
        fromReservationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fromReservationBtnMouseReleased(evt);
            }
        });
        getContentPane().add(fromReservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fromReservationBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromReservationBtnMouseReleased
        // TODO add your handling code here:
        RezervationChoose resvChooseWin = new RezervationChoose();
        resvChooseWin.setVisible(true);
        resvChooseWin.populateListReservations();
        
        resvChooseWin.chooseBtn.addActionListener(e ->{
            
            Reservation resv = resvChooseWin.reservationsList.getSelectedValue();
            
            dateFromField.setText(resv.dateFromGet().format(MainLogic.getDateFormat()));
            dateToField.setText(resv.dateToGet().format(MainLogic.getDateFormat()));
            customerChosen.setText(resv.getCust().toString());
            customer = resv.getCust();
            roomChosen.setText(resv.getRoom().toString());
            room = resv.getRoom();
            
            Accomodation newAccm = Accomodation.getInstanceFromReservation(resv);
            newAccm.setPrice(newAccm.calculateAccmPrice(true));
            
            priceAccmLbl.setText(String.valueOf(newAccm.getPrice()));
            
            resvChooseWin.setVisible(false);
            createReservationBtn.setEnabled(false);
            
            
        });
        
    }//GEN-LAST:event_fromReservationBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    public javax.swing.JButton createAccmBtn;
    public javax.swing.JButton createReservationBtn;
    private javax.swing.JLabel customerChosen;
    private javax.swing.JFormattedTextField dateFromField;
    private javax.swing.JFormattedTextField dateToField;
    private javax.swing.JButton fromReservationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel priceAccmLbl;
    private javax.swing.JLabel roomChosen;
    private javax.swing.JButton setCustomer;
    private javax.swing.JButton setRoom;
    // End of variables declaration//GEN-END:variables
}
