/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;

import java.util.Locale;

/**
 *
 * @author DADO
 */
public class setLang extends javax.swing.JFrame {
    
    MainLogic logic;
    
    /**
     * Creates new form setLang
     */
    public setLang() {
        this.logic = new MainLogic();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        langCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose your language");
        setMinimumSize(new java.awt.Dimension(300, 47));

        langCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sk", "en" }));
        getContentPane().add(langCombo, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Vyberte jazyk / choose language:");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        OkBtn.setText("OK");
        OkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OkBtnMouseReleased(evt);
            }
        });
        jPanel1.add(OkBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkBtnMouseReleased
        // TODO add your handling code here:
        
        Locale lang = getLanguageSelected();
        MainLogic.setLocaleAndRBundle(lang);
        logic.startDashboard(logic);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_OkBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setLang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setLang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setLang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setLang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setLang().setVisible(true);
            }
        });
    }
    
    
    public Locale getLanguageSelected(){
        
        switch (langCombo.getSelectedItem().toString()) {
            case "sk":
                return new Locale("sk","SK");
                
            case "en":
                return new Locale("en","US");
                
            default:
                throw new AssertionError();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OkBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> langCombo;
    // End of variables declaration//GEN-END:variables
}
